### PR TITLE
Telephone Number Validator

### PR DESCRIPTION
**Pull request by zainabbehzad**
Telephone Number Validator:
- First of all I have created a repo according the project requirements.
- I have used the Gitflow.
- I have added the JavaScript linters configuration in my project.
- Then fixed all Linters errors.
- Added the HTML, CSS, and JavaScript files.
- Added a README.md file.
- Then I have added codes to create my project structer(HTML ) give them styles(CSS) and added actions to my codes(JavaScript).
- When I finished my codes I tested my project codes in FreeCodeCamp website that passed all its requirements.

Screenshot (40)

### CODE REVIEW

**Comment by zainabbehzad** [comment]
@Marwa-Sadat
Hello Marwa jan
Please review my project

**Comment by zainabbehzad** [comment]
@ahzamir
Hello sir!
Hope you doing well.
Kindly review my project.

**Comment by Marwa-Sadat** [comment]
@Marwasadat approved this pull request.  
Hi @Zainab-Behzad 🙋‍♀,

Wow, this is fantastic! 💯 You've done an amazing job implementing all the requirements for the "Telephone-Number-Validator" project. 🥳 Your feature is complete! Congratulations!!! 🎉

- *[REQUIRED]* Share your project on this GROUP with a simple Proud Moment text and a screenshot of your project. Add your project link at the end as a GitHub source code reference and post.
- Share your project on your LinkedIn account with a Proud Moment text and a screenshot.
- Well done, great design implemented! 🎯🎉👍

Status: Approved ✅
*Highlights 🌟*
- 🎉 Great design implemented
- ✔ Created a professional repo (You created a repository with your project name)
- ✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
- ✔ Commit messages are meaningful
- ✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
- ✔ No linter errors (All linters checks have been passed 🟢)
- ✔ You have followed the Telephone-Number-Validator project task and committed using the command line
- ✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
- ✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
- ✔ Your code is clean
- ✔ Your repo has a professional README.md file
- ✔ Your repo has been reviewed by your partner
- ✔ Your design is responsive

Cheers 🥂 and happy coding!!! 
 Feel free to tag me @Marwa-Sadat if you have any questions.

**Comment by zainabbehzad** [comment]
@Marwa-Sadat 
Thanks Marwa jan .

**Comment by Marwa-Sadat** [comment]
@Marwasadat approved this pull request.
Hi @Zainab-Behzad 🙋‍♀,

Wow, this is fantastic! 💯 You've done an amazing job implementing all the requirements for the "Telephone-Number-Validator" project. 🥳 Your feature is complete! Congratulations!!! 🎉

    [REQUIRED] Share your project on this GROUP with a simple Proud Moment text and a screenshot of your project. Add your project link at the end as a GitHub source code reference and post.
    Share your project on your LinkedIn account with a Proud Moment text and a screenshot.
    Well done, great design implemented! 🎯🎉👍

Status: Approved ✅
Highlights 🌟

    🎉 Great design implemented
    ✔ Created a professional repo (You created a repository with your project name)
    ✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
    ✔ Commit messages are meaningful
    ✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
    ✔ No linter errors (All linters checks have been passed 🟢)
    ✔ You have followed the Telephone-Number-Validator project task and committed using the command line
    ✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
    ✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

    ✔ Your code is clean
    ✔ Your repo has a professional README.md file
    ✔ Your design is responsive

Cheers 🥂 and happy coding!!!
Feel free to tag me @Marwa-Sadat if you have any questions.

**Comment by Marwa-Sadat** [comment]
@marwasadat approved this pull request. 

 
Hi @Zainab-Behzad 🙋‍♀,


Wow, this is fantastic! 💯 You've done an amazing job implementing all the requirements for the "Telephone-Number-Validator" project. 🥳 Your feature is complete! Congratulations!!! 🎉

- *[REQUIRED]* Share your project on this GROUP with a simple Proud Moment text and a screenshot of your project. Add your project link at the end as a GitHub source code reference and post.
- Share your project on your LinkedIn account with a Proud Moment text and a screenshot.
- Well done, great design implemented! 🎯🎉👍

Status: Approved ✅

There's nothing left to say other than to merge your branch. 🎉🎯✅👍😊🥳

*Highlights 🌟*
- 🎉 Great design implemented
- ✔ Created a professional repo (You created a repository with your project name)
- ✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
- ✔ Commit messages are meaningful
- ✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
- ✔ No linter errors (All linters checks have been passed 🟢)
- ✔ You have followed the Telephone-Number-Validator project task and committed using the command line
- ✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
- ✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
- ✔ Your code is clean
- ✔ Your repo has a professional README.md file
- ✔ Your design is responsive

Cheers 🥂 and happy coding!!! 
 Feel free to tag me @Marwa-Sadat if you have any questions.

**Review by ahzamir — CHANGES_REQUESTED** [review]
@zainabbehzad 

- Well done you have implemented lots of requirements but still you have a small issue in your mobile version design:
  - In the mobile version your page scrolls vertically which is wrong and your elements should be shown in the middle sso solve this issue and request a re-review by mentioning me here using my username:
  
image

**Comment by zainabbehzad** [comment]
@ahzamir 
Hello sir!
hope you doing well
please review my project.
sir I don't know what is the problem that for me it is responsive for all mobile versions and does not scrolls vertically but for you scroll vertically. This issue was on 2 of my last projects too.

**Review by ahzamir — APPROVED** [review]
### Hi @zainabbehzad 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by zainabbehzad** [comment]
@ahzamir 
Thanks dear Sir!

**Pull request merged**
